//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizOfLegends.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizOfLegends.Lang.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quiz Of Legends.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find the Champion.
        /// </summary>
        public static string FindChampion {
            get {
                return ResourceManager.GetString("FindChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find the Skills.
        /// </summary>
        public static string FindSkills {
            get {
                return ResourceManager.GetString("FindSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Games Modes.
        /// </summary>
        public static string GameModes {
            get {
                return ResourceManager.GetString("GameModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MCQ.
        /// </summary>
        public static string MCQ {
            get {
                return ResourceManager.GetString("MCQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What ressource allows Aatrox to use his skills ?.
        /// </summary>
        public static string MCQ_Q1 {
            get {
                return ResourceManager.GetString("MCQ_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mana.
        /// </summary>
        public static string MCQ_Q1_A {
            get {
                return ResourceManager.GetString("MCQ_Q1_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Health.
        /// </summary>
        public static string MCQ_Q1_B {
            get {
                return ResourceManager.GetString("MCQ_Q1_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Energy.
        /// </summary>
        public static string MCQ_Q1_C {
            get {
                return ResourceManager.GetString("MCQ_Q1_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nothing.
        /// </summary>
        public static string MCQ_Q1_D {
            get {
                return ResourceManager.GetString("MCQ_Q1_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        public static string MCQ_Q1_R {
            get {
                return ResourceManager.GetString("MCQ_Q1_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à With whom does Aatrox share the same skin ?.
        /// </summary>
        public static string MCQ_Q10 {
            get {
                return ResourceManager.GetString("MCQ_Q10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kha&apos;zix.
        /// </summary>
        public static string MCQ_Q10_A {
            get {
                return ResourceManager.GetString("MCQ_Q10_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nocturne.
        /// </summary>
        public static string MCQ_Q10_B {
            get {
                return ResourceManager.GetString("MCQ_Q10_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elise.
        /// </summary>
        public static string MCQ_Q10_C {
            get {
                return ResourceManager.GetString("MCQ_Q10_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syndra.
        /// </summary>
        public static string MCQ_Q10_D {
            get {
                return ResourceManager.GetString("MCQ_Q10_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D.
        /// </summary>
        public static string MCQ_Q10_R {
            get {
                return ResourceManager.GetString("MCQ_Q10_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is the maximum attack speed bonus Aatrox can earn thanks to the passive of Blood Well ?.
        /// </summary>
        public static string MCQ_Q2 {
            get {
                return ResourceManager.GetString("MCQ_Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 35%.
        /// </summary>
        public static string MCQ_Q2_A {
            get {
                return ResourceManager.GetString("MCQ_Q2_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 40%.
        /// </summary>
        public static string MCQ_Q2_B {
            get {
                return ResourceManager.GetString("MCQ_Q2_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 45%.
        /// </summary>
        public static string MCQ_Q2_C {
            get {
                return ResourceManager.GetString("MCQ_Q2_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 50%.
        /// </summary>
        public static string MCQ_Q2_D {
            get {
                return ResourceManager.GetString("MCQ_Q2_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D.
        /// </summary>
        public static string MCQ_Q2_R {
            get {
                return ResourceManager.GetString("MCQ_Q2_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How much life does Aatrox lose when he uses Dark flight ?.
        /// </summary>
        public static string MCQ_Q3 {
            get {
                return ResourceManager.GetString("MCQ_Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5%.
        /// </summary>
        public static string MCQ_Q3_A {
            get {
                return ResourceManager.GetString("MCQ_Q3_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 10%.
        /// </summary>
        public static string MCQ_Q3_B {
            get {
                return ResourceManager.GetString("MCQ_Q3_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 15%.
        /// </summary>
        public static string MCQ_Q3_C {
            get {
                return ResourceManager.GetString("MCQ_Q3_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 20%.
        /// </summary>
        public static string MCQ_Q3_D {
            get {
                return ResourceManager.GetString("MCQ_Q3_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        public static string MCQ_Q3_R {
            get {
                return ResourceManager.GetString("MCQ_Q3_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  What&apos;s the ratio&apos;s type on Aatrox&apos;s Blade of Torment ?.
        /// </summary>
        public static string MCQ_Q4 {
            get {
                return ResourceManager.GetString("MCQ_Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AD.
        /// </summary>
        public static string MCQ_Q4_A {
            get {
                return ResourceManager.GetString("MCQ_Q4_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AP.
        /// </summary>
        public static string MCQ_Q4_B {
            get {
                return ResourceManager.GetString("MCQ_Q4_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AD &amp; AP.
        /// </summary>
        public static string MCQ_Q4_C {
            get {
                return ResourceManager.GetString("MCQ_Q4_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string MCQ_Q4_D {
            get {
                return ResourceManager.GetString("MCQ_Q4_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C.
        /// </summary>
        public static string MCQ_Q4_R {
            get {
                return ResourceManager.GetString("MCQ_Q4_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What key do you need to push to use Aatrox&apos;s Blood Price ?.
        /// </summary>
        public static string MCQ_Q5 {
            get {
                return ResourceManager.GetString("MCQ_Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A.
        /// </summary>
        public static string MCQ_Q5_A {
            get {
                return ResourceManager.GetString("MCQ_Q5_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Z.
        /// </summary>
        public static string MCQ_Q5_B {
            get {
                return ResourceManager.GetString("MCQ_Q5_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E.
        /// </summary>
        public static string MCQ_Q5_C {
            get {
                return ResourceManager.GetString("MCQ_Q5_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à R.
        /// </summary>
        public static string MCQ_Q5_D {
            get {
                return ResourceManager.GetString("MCQ_Q5_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        public static string MCQ_Q5_R {
            get {
                return ResourceManager.GetString("MCQ_Q5_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who says : &quot;This battle will be my Masterpiece&quot; ?.
        /// </summary>
        public static string MCQ_Q6 {
            get {
                return ResourceManager.GetString("MCQ_Q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aatrox.
        /// </summary>
        public static string MCQ_Q6_A {
            get {
                return ResourceManager.GetString("MCQ_Q6_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mordekaiser.
        /// </summary>
        public static string MCQ_Q6_B {
            get {
                return ResourceManager.GetString("MCQ_Q6_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rengar.
        /// </summary>
        public static string MCQ_Q6_C {
            get {
                return ResourceManager.GetString("MCQ_Q6_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Draven.
        /// </summary>
        public static string MCQ_Q6_D {
            get {
                return ResourceManager.GetString("MCQ_Q6_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A.
        /// </summary>
        public static string MCQ_Q6_R {
            get {
                return ResourceManager.GetString("MCQ_Q6_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who says : &quot;Fight as a hero or die as a coward&quot; ?.
        /// </summary>
        public static string MCQ_Q7 {
            get {
                return ResourceManager.GetString("MCQ_Q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aatrox.
        /// </summary>
        public static string MCQ_Q7_A {
            get {
                return ResourceManager.GetString("MCQ_Q7_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Darius.
        /// </summary>
        public static string MCQ_Q7_B {
            get {
                return ResourceManager.GetString("MCQ_Q7_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Olaf.
        /// </summary>
        public static string MCQ_Q7_C {
            get {
                return ResourceManager.GetString("MCQ_Q7_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xin Zaho.
        /// </summary>
        public static string MCQ_Q7_D {
            get {
                return ResourceManager.GetString("MCQ_Q7_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A.
        /// </summary>
        public static string MCQ_Q7_R {
            get {
                return ResourceManager.GetString("MCQ_Q7_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who says : &quot;Peace is the greattest of all lies&quot; ?.
        /// </summary>
        public static string MCQ_Q8 {
            get {
                return ResourceManager.GetString("MCQ_Q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hecarim.
        /// </summary>
        public static string MCQ_Q8_A {
            get {
                return ResourceManager.GetString("MCQ_Q8_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Varus.
        /// </summary>
        public static string MCQ_Q8_B {
            get {
                return ResourceManager.GetString("MCQ_Q8_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aatrox.
        /// </summary>
        public static string MCQ_Q8_C {
            get {
                return ResourceManager.GetString("MCQ_Q8_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xerath.
        /// </summary>
        public static string MCQ_Q8_D {
            get {
                return ResourceManager.GetString("MCQ_Q8_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D.
        /// </summary>
        public static string MCQ_Q8_R {
            get {
                return ResourceManager.GetString("MCQ_Q8_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who&apos;s Aatrox&apos;s Nemesis ?.
        /// </summary>
        public static string MCQ_Q9 {
            get {
                return ResourceManager.GetString("MCQ_Q9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Darius.
        /// </summary>
        public static string MCQ_Q9_A {
            get {
                return ResourceManager.GetString("MCQ_Q9_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Viktor.
        /// </summary>
        public static string MCQ_Q9_B {
            get {
                return ResourceManager.GetString("MCQ_Q9_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tryndamere.
        /// </summary>
        public static string MCQ_Q9_C {
            get {
                return ResourceManager.GetString("MCQ_Q9_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thresh.
        /// </summary>
        public static string MCQ_Q9_D {
            get {
                return ResourceManager.GetString("MCQ_Q9_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C.
        /// </summary>
        public static string MCQ_Q9_R {
            get {
                return ResourceManager.GetString("MCQ_Q9_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Game.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
